Feature split train dir reduc
AI-vidence/antakia-core pull request #7
Opened 2024-03-25 13:28 UTC by walidamrouche

2024-03-25 13:46 UTC, phulot requested changes

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +            sample_size: int | None = None,
est ce que tu peux changer de nom, peut être plus utiliser fit_sample_num

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +
git sert à maintenir l'historique, pas besoin de pousser les commentaires

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +            raise ValueError(f"Sample size ({sample_size}) is greater than the Dataset size ({self.X.shape[0]})")
prendre le min entre le sample_size et len(X)

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +            X_red = dim_red_model.fit(self.X.sample(n=sample_size)).transform(self.X)
plus besoin de faire de distinctions ici, tout le monde doit passer par fit puis transform

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduction.py
> +                       sample_size: int | None = None,
tu peux le mettre directement dans les kwargs, ça marchera

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/data_handler/projected_values.py
> +                       sample_size: int | None = None,
on va passer cette variable dans l'init plutot, c'est une limite globale qui sera gérée par variable d'environnement

2024-03-25 13:46 UTC, phulot commented on src/antakia_core/data_handler/projected_values.py
> +    def compute(self, projection: Proj, progress_callback: Callable | None, sample_size: int | None = None):
idem

2024-03-25 13:46 UTC, phulot commented on tests/data_handler/test_projected_values.py
> +        pv.compute(proj, self.callable)
est ce que tu peux vérifier que le progress termine bien à 100 ?

2024-03-25 13:46 UTC, phulot commented on tests/data_handler/test_projected_values.py
>          assert isinstance(pv.get_projection(proj), pd.DataFrame)
ici il faut tester avec et sans callback et vérifier que le callback a bien été appelé avec 100 à la fin

2024-03-25 13:58 UTC, walidamrouche commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +            raise ValueError(f"Sample size ({sample_size}) is greater than the Dataset size ({self.X.shape[0]})")
donc je mets la valeur par défault de sample_size à np.inf par exemple ?

2024-03-26 10:45 UTC, phulot requested changes

2024-03-26 10:45 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduction.py
> +                 ):
il manque l'argument dans le super(-.__init__())

2024-03-26 10:45 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduction.py
> +                 ):
idem

2024-03-26 10:45 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduction.py
> +                 ):
idem

2024-03-26 10:45 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduction.py
> +                 ):
idem

2024-03-26 10:45 UTC, phulot commented on tests/utils_fct.py
> +
pourquoi?

2024-03-29 14:27 UTC, phulot requested changes

2024-03-29 14:27 UTC, phulot commented on tests/data_handler/test_projected_values.py
> +        self.callable = DummyCallable()
est ce que tu peux cahnger de nom ? callable est trop générique

2024-04-23 09:49 UTC, phulot commented on src/antakia_core/utils/splittable_callback.py
> +        super().__init__()
init ??

2024-04-23 09:49 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +        X_red = dim_red_model.fit(self.X.sample(n=fit_sample_num)).transform(self.X)
est ce qu'on pourrait aussi gérer le cas où on a pas accès à deux méthodes distinctes fit et transform? mais uniquement à fit_transform

2024-04-23 12:47 UTC, walidamrouche commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +        X_red = dim_red_model.fit(self.X.sample(n=fit_sample_num)).transform(self.X)
ok

2024-04-23 14:18 UTC, phulot commented on src/antakia_core/data_handler/projected_values.py
> +    def __init__(self, X: pd.DataFrame, y: pd.Series, fit_sample_num: int | None = None):
fit_sample_num ne sert à rien ici

2024-04-23 14:49 UTC, merged