Unit tests
AI-vidence/antakia-core pull request #8
Opened 2024-03-28 16:38 UTC by walidamrouche

2024-03-29 16:54 UTC, phulot requested changes

2024-03-29 16:54 UTC, phulot commented on src/antakia_core/compute/model_subtitution/model_interface.py
> +    df = pd.read_csv('C:/1_Programmation/python/aividence/antakia/examples/data/california_housing.csv'
je ne veux pas voir de path locaux dans les fichiers

2024-03-29 16:54 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduc_method.py
> +                              progress_updated=callback.call)
pas besoin de call ici

2024-03-29 16:54 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduc_method.py
> +                              progress_updated=callback.call)
idem

2024-03-29 16:54 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduc_method.py
> +                              progress_updated=callback.call)
je te laisse changer les suivants aussi

2024-03-29 16:54 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduction.py
> +        dr_pca = PCADimReduc(self.X, 2, callback.call)
idem pas besoin des call

2024-03-29 16:54 UTC, phulot commented on tests/compute/model_substitution/test_model_interface.py
> +        pass
à implémenter ou à enlever

2024-03-29 16:54 UTC, phulot commented on tests/compute/model_substitution/test_model_interface.py
> +        int_mod = InterpretableModels(mean_squared_error)
à résoudre avant de pousser

2024-03-29 16:54 UTC, phulot commented on tests/compute/model_substitution/test_model_interface.py
> +        int_mod = InterpretableModels('MSE')
il faut avoir une approche un peu plus poussée sur les scores, pas mal de bug peuvent venir de là

2024-03-29 16:54 UTC, phulot commented on tests/compute/model_substitution/test_model_interface.py
> +class TestInterpretableModels(TestCase):
il faudra qu'on rediscute des test de cette classe

2024-03-29 16:54 UTC, phulot commented on tests/data_handler/test_region_set.py
> +        self.mask = dummy_mask(self.y_train, random_seed=14).astype(bool)
pourquoi est ce qu'on a besoin de changer tout ça ?

2024-03-29 16:54 UTC, phulot commented on tests/utils_fct.py
> +        self.calls.append(args)
à retirer, on a pas besoin de ça

2024-03-29 16:54 UTC, phulot commented on tests/utils_fct.py
> -def generate_df_series():
il y a dummy datasets pour ça

2024-04-16 13:33 UTC, phulot commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +        return (X - X.mean()) / std * mi
il manque un retour à la ligne

2024-04-16 13:33 UTC, phulot commented on src/antakia_core/data_handler/projected_values.py
> +        self._projected_values[projection] = projected_values
ici aussi il manque une ligne

2024-04-16 13:33 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduc_method.py
> +        drm4 = DimReducMethod(2,
découper en sous tests

2024-04-16 13:33 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduc_method.py
> +        assert np.round(drm.scale_value_space(X, y,self.callback )[::], 6).equals(expected)
il manque une ligne en fin de fichier

2024-04-16 13:33 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduction.py
> +        ])
on teste quoi au juste ?

2024-04-16 13:33 UTC, phulot commented on tests/compute/dim_reduction/test_dim_reduction.py
> +        ])
idem pour les suivants

2024-04-16 13:33 UTC, phulot commented on tests/compute/skope_rule/test_skope_rule.py
> +        # test for a min rule
est ce qu'on peut séparer les tests ?

2024-04-16 14:15 UTC, walidamrouche commented on src/antakia_core/compute/dim_reduction/dim_reduc_method.py
> +        return (X - X.mean()) / std * mi
résolu

2024-04-16 14:20 UTC, walidamrouche commented on tests/compute/dim_reduction/test_dim_reduc_method.py
> +        drm4 = DimReducMethod(2,
résolu

2024-04-16 14:39 UTC, walidamrouche commented on tests/compute/dim_reduction/test_dim_reduction.py
> +        ])
j'ai rajouté des tests sur le type et la présence de la méthode fit

2024-04-16 14:45 UTC, walidamrouche commented on tests/compute/skope_rule/test_skope_rule.py
> +        # test for a min rule
c'est fait

2024-04-23 14:49 UTC, merged